default:
  has_layout:   on
  layout:       bmclayout
  javascripts:  [ -* ]
  stylesheets:  [ /lib/css/modal, /lib/css/bmc ]

bmcSuccess: 
  has_layout:   on
  layout:       bmclayout
  javascripts:  [ -* ]
  stylesheets:  [ /lib/css/bmc ]

bmc1Success:
  has_layout:     on
  layout:         bmc1layout
  javascripts:    [ -*, /lib/js/jquery-1.3.1.min.js, /lib/js/bmc1modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ -*, /lib/css/bmc1modal, /lib/css/bmc1 ]

bmc4Success:
  has_layout:     on
  layout:       bmclayout
  javascripts:  [ -* ]
  stylesheets:  [ -*, /lib/css/bmc5 ]

varpartnerlistSuccess:
  has_layout:     on
  layout:         bmc1layout
  javascripts:    [ -*, /lib/js/bmc1modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ -*, /lib/css/bmc1modal, /lib/css/bmc1 ]

supportSuccess:
  has_layout:     off
  layout:         bmc1layout
  javascripts:    [ -* ]
  stylesheets:    [ -* ]

updateLoginDataSuccess:
  has_layout:     off
  javascripts:    [ -* ]
  stylesheets:    [ -* ]

helpSuccess:
  has_layout:     on
  layout:         helplayout
  javascripts:    [ -* ]
  stylesheets:    [ -*, /lib/css/bmc ]

bmc2helpSuccess:
  has_layout:     on
  layout:         helplayout
  javascripts:    [ -*, /lib/js/jquery.v1.4.2.min.js ]
  stylesheets:    [ -*, /lib/css/bmc ]

previewSuccess:
  has_layout:     off
  layout:         helplayout
  javascripts:    [ -* ]
  stylesheets:    [ -*, /lib/css/bmc ]