<?php
// This file generated by Propel  convert-conf target
// from XML runtime conf file /opt/borhan/app/alpha/config/runtime-conf.xml
return array (
  'datasources' => 
  array (
    'borhan' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'phptype' => 'mysql',
        'database' => 'borhan',
        'hostspec' => 'localhost',
        'username' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'borhan',
  ),
  'log' => 
  array (
    'ident' => 'borhan',
    'level' => '7',
  ),
  'generator_version' => '1.4.2',
  'classmap' => 
  array (
    'ScheduledTaskProfileTableMap' => 'lib/model/map/ScheduledTaskProfileTableMap.php',
    'ScheduledTaskProfilePeer' => 'lib/model/ScheduledTaskProfilePeer.php',
    'ScheduledTaskProfile' => 'lib/model/ScheduledTaskProfile.php',
  ),
);