<?php
// This file generated by Propel  convert-conf target
// from XML runtime conf file /Users/hila.karimov/Documents/borhan/app/alpha/config/runtime-conf.xml
return array (
  'datasources' => 
  array (
    'borhan' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'phptype' => 'mysql',
        'database' => 'borhan',
        'hostspec' => 'localhost',
        'username' => 'root',
        'password' => 'root',
      ),
    ),
    'default' => 'borhan',
  ),
  'log' => 
  array (
    'ident' => 'borhan',
    'level' => '7',
  ),
  'generator_version' => '1.4.2',
  'classmap' => 
  array (
    'BusinessProcessServerTableMap' => 'lib/model/map/BusinessProcessServerTableMap.php',
    'BusinessProcessServerPeer' => 'lib/model/BusinessProcessServerPeer.php',
    'BusinessProcessServer' => 'lib/model/BusinessProcessServer.php',
    'BusinessProcessCaseTableMap' => 'lib/model/map/BusinessProcessCaseTableMap.php',
    'BusinessProcessCasePeer' => 'lib/model/BusinessProcessCasePeer.php',
    'BusinessProcessCase' => 'lib/model/BusinessProcessCase.php',
  ),
);